export const consensusData = [ // Tankathon 4/18
  {n: 1, t: 'Titans', p: 'Cam Ward'},
  {n: 2, t: 'Browns', p: 'Travis Hunter'},
  {n: 3, t: 'Giants', p: 'Abdul Carter'},
  {n: 4, t: 'Patriots', p: 'Will Campbell'},
  {n: 5, t: 'Jaguars', p: 'Mason Graham'},
  {n: 6, t: 'Raiders', p: 'Ashton Jeanty'},
  {n: 7, t: 'Jets', p: 'Armand Membou'},
  {n: 8, t: 'Panthers', p: 'Jalon Walker'},
  {n: 9, t: 'Saints', p: 'Shedeur Sanders'},
  {n: 10, t: 'Bears', p: 'Kelvin Banks Jr'},
  {n: 11, t: '49ers', p: 'Will Johnson'},
  {n: 12, t: 'Cowboys', p: 'Tetairoa McMillan'},
  {n: 13, t: 'Dolphins', p: 'Malaki Starks'},
  {n: 14, t: 'Colts', p: 'Tyler Warren'},
  {n: 15, t: 'Falcons', p: 'Mike Green'},
  {n: 16, t: 'Cardinals', p: 'Kenneth Grant'},
  {n: 17, t: 'Bengals', p: 'Shemar Stewart'},
  {n: 18, t: 'Seahawks', p: 'Grey Zabel'},
  {n: 19, t: 'Buccaneers', p: 'Jihaad Campbell'},
  {n: 20, t: 'Broncos', p: 'Omarion Hampton'},
  {n: 21, t: 'Steelers', p: 'Jaxson Dart'},
  {n: 22, t: 'Chargers', p: 'Colston Loveland'},
  {n: 23, t: 'Packers', p: 'Matthew Golden'},
  {n: 24, t: 'Vikings', p: 'Nick Emmanwori'},
  {n: 25, t: 'Texans', p: 'Josh Simmons'},
  {n: 26, t: 'Rams', p: 'Jahdae Barron'},
  {n: 27, t: 'Ravens', p: 'Mykel Williams'},
  {n: 28, t: 'Lions', p: 'Tyler Booker'},
  {n: 29, t: 'Commanders', p: 'James Pearce Jr'},
  {n: 30, t: 'Bills', p: 'Walter Nolen'},
  {n: 31, t: 'Chiefs', p: 'Josh Conerly Jr'},
  {n: 32, t: 'Eagles', p: 'Derrick Harmon'},
];